"""
LLM orchestration service: builds prompts, calls providers, streams SSE events.

Workflow (sequential):
  1. [Optional] Edison Scientific literature search → grounded citations
  2. OpenAI / Ollama structuring call → JSON effects list
"""

import json
from itertools import combinations
from typing import AsyncGenerator, TYPE_CHECKING

if TYPE_CHECKING:
    from api.models.requests import SuggestEffectsRequest

# ---------------------------------------------------------------------------
# Fixed system instructions (not user-editable)
# ---------------------------------------------------------------------------
_SYSTEM_INSTRUCTIONS = """\
You are a scientific advisor for experimental design in chemistry and materials science.
Your task is to recommend which model terms (main effects, interactions, quadratic effects) \
are most scientifically justified for an optimal experimental design, based on domain \
knowledge and published literature.

IMPORTANT: You must ONLY select effects from the provided "Available effects" list. \
Do not suggest effects that are not in the list. Do not invent or modify variable names. \
Select the minimum necessary set for a well-powered design — do not include effects you \
cannot justify scientifically.\
"""

# ---------------------------------------------------------------------------
# JSON schema for structured output
# OpenAI strict mode requires: additionalProperties=false on all objects,
# all properties in required.  We use arrays-of-objects for reasoning/confidence
# instead of free-form dicts to satisfy that constraint.
# ---------------------------------------------------------------------------
EFFECTS_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "effects": {
            "type": "array",
            "description": "Selected effect strings taken verbatim from the available effects list.",
            "items": {"type": "string"},
        },
        "reasoning": {
            "type": "array",
            "description": "Scientific reasoning for each selected effect.",
            "items": {
                "type": "object",
                "properties": {
                    "effect": {"type": "string"},
                    "reason": {"type": "string"},
                },
                "required": ["effect", "reason"],
                "additionalProperties": False,
            },
        },
        "confidence": {
            "type": "array",
            "description": "Confidence level for each selected effect.",
            "items": {
                "type": "object",
                "properties": {
                    "effect": {"type": "string"},
                    "level": {"type": "string", "enum": ["high", "medium", "low"]},
                },
                "required": ["effect", "level"],
                "additionalProperties": False,
            },
        },
        "sources": {
            "type": "array",
            "description": (
                "Literature sources supporting these recommendations. "
                "Include specific citations (author, year, journal) when available. "
                "If no specific sources are known, return an empty array."
            ),
            "items": {"type": "string"},
        },
        "disclaimer": {
            "type": "string",
            "description": (
                "Standard disclaimer about the AI-generated nature of these recommendations."
            ),
        },
    },
    "required": ["effects", "reasoning", "confidence", "sources", "disclaimer"],
    "additionalProperties": False,
}

_DEFAULT_DISCLAIMER = (
    "These recommendations are generated by an AI model and should be reviewed by "
    "a domain expert. Sources should be independently verified before citation."
)

# ---------------------------------------------------------------------------
# Prompt assembly helpers
# ---------------------------------------------------------------------------

def _format_variable(v: dict) -> str:
    vtype = v.get("type", "real")
    name = v["name"]
    if vtype == "categorical":
        cats = v.get("categories", [])
        return f"- {name} (categorical): {cats}"
    lo = v.get("lower_bound", "?")
    hi = v.get("upper_bound", "?")
    unit = v.get("unit") or ""
    unit_str = f" {unit}" if unit else ""
    return f"- {name} ({vtype}): {lo}–{hi}{unit_str}"


def _build_effects_lists(
    variables: list[dict],
) -> tuple[list[str], list[str], list[str]]:
    cont_types = {"real", "integer", "discrete", None}
    all_names = [v["name"] for v in variables]
    cont_names = [v["name"] for v in variables if v.get("type") in cont_types]
    interactions = [f"{a}*{b}" for a, b in combinations(all_names, 2)]
    quadratics = [f"{n}**2" for n in cont_names]
    return all_names, interactions, quadratics


def build_user_prompt(
    variables: list[dict],
    system_context: str,
    literature_context: str | None = None,
) -> str:
    main, interactions, quadratics = _build_effects_lists(variables)
    var_lines = "\n".join(_format_variable(v) for v in variables)

    lit_section = ""
    if literature_context:
        lit_section = (
            f"\nLiterature context (retrieved from scientific database — "
            f"citations included):\n{literature_context}\n"
        )

    interactions_str = ", ".join(interactions) if interactions else "(none — fewer than 2 variables)"
    quadratics_str = ", ".join(quadratics) if quadratics else "(none — no continuous variables)"

    return (
        f"System description: {system_context}"
        f"{lit_section}\n"
        f"Variable space:\n{var_lines}\n\n"
        f"Available effects to select from:\n"
        f"  Main effects:    {', '.join(main)}\n"
        f"  Interactions:    {interactions_str}\n"
        f"  Quadratic:       {quadratics_str}\n\n"
        f"Recommend which effects are most likely to be scientifically significant "
        f"for this system{' based on the literature context above' if literature_context else ''}."
    )


def build_edison_query(variables: list[dict], system_context: str) -> str:
    var_desc = "; ".join(
        f"{v['name']} ({v.get('type', 'real')})" for v in variables
    )
    return (
        f"What main effects, interactions, and quadratic/curvature terms are "
        f"scientifically significant for the following experimental system?\n\n"
        f"System: {system_context}\n\n"
        f"Variables: {var_desc}\n\n"
        f"Specifically: (1) Which variables most strongly affect the target response? "
        f"(2) Which pairwise interactions are likely important? "
        f"(3) Which variables likely show non-linear (quadratic/curvature) behavior? "
        f"Please cite specific literature sources where possible."
    )


# ---------------------------------------------------------------------------
# Provider factory
# ---------------------------------------------------------------------------

def _get_structuring_provider(config: "LLMProviderConfig"):  # noqa: F821
    provider = config.provider
    if provider == "openai":
        from api.services.providers.openai_provider import OpenAIProvider
        return OpenAIProvider(api_key=config.api_key, model=config.model)
    if provider == "ollama":
        from api.services.providers.ollama_provider import OllamaProvider
        base_url = (config.base_url or "http://localhost:11434").rstrip("/")
        # The OpenAI SDK appends /chat/completions to base_url, so it must
        # include Ollama's /v1 prefix (e.g. http://localhost:11434/v1).
        if not base_url.endswith("/v1"):
            base_url = base_url + "/v1"
        return OllamaProvider(model=config.model, base_url=base_url)
    raise ValueError(f"Unknown structuring provider: {provider!r}")


# ---------------------------------------------------------------------------
# SSE helper
# ---------------------------------------------------------------------------

def _sse(data: dict) -> str:
    return f"data: {json.dumps(data)}\n\n"


# ---------------------------------------------------------------------------
# Main streaming orchestrator
# ---------------------------------------------------------------------------

async def suggest_effects_stream(
    variables: list[dict],
    request: "SuggestEffectsRequest",
) -> AsyncGenerator[str, None]:
    """
    Yields Server-Sent Event strings.

    Event shapes:
      {"status": "searching_literature", "message": "..."}
      {"status": "literature_complete",  "message": "..."}
      {"status": "literature_warning",   "message": "..."}
      {"status": "literature_error",     "message": "..."}
      {"status": "structuring",          "message": "..."}
      {"status": "complete",             "result": {...}}
      {"status": "error",                "message": "..."}
    """
    literature_context: str | None = None

    # ------------------------------------------------------------------
    # Stage 1 (optional): Edison Scientific literature search
    # ------------------------------------------------------------------
    if request.edison_config:
        yield _sse({
            "status": "searching_literature",
            "message": "Querying literature database (Edison Scientific)…",
        })
        try:
            from api.services.providers.edison_provider import EdisonLiteratureProvider
            edison = EdisonLiteratureProvider(
                api_key=request.edison_config.api_key,
                job_type=request.edison_config.job_type,
            )
            query = build_edison_query(variables, request.system_context)
            answer, formatted_answer, has_answer = await edison.search_literature(query)

            if has_answer and formatted_answer:
                literature_context = formatted_answer
                yield _sse({
                    "status": "literature_complete",
                    "message": "Literature search complete — passing context to structuring model.",
                })
            else:
                yield _sse({
                    "status": "literature_warning",
                    "message": (
                        "Edison did not find a confident answer. "
                        "Proceeding without literature context."
                    ),
                })
        except Exception as exc:
            yield _sse({
                "status": "literature_error",
                "message": f"Literature search failed ({exc}). Proceeding without.",
            })

    # ------------------------------------------------------------------
    # Stage 2: Structuring model (OpenAI / Ollama)
    # ------------------------------------------------------------------
    provider_label = f"{request.structuring_provider.provider}/{request.structuring_provider.model}"
    yield _sse({
        "status": "structuring",
        "message": f"Extracting structured effects with {provider_label}…",
    })

    try:
        provider = _get_structuring_provider(request.structuring_provider)
        user_prompt = build_user_prompt(variables, request.system_context, literature_context)
        result = await provider.suggest_effects(_SYSTEM_INSTRUCTIONS, user_prompt, EFFECTS_SCHEMA)

        # Ensure required keys are present with safe defaults
        result.setdefault("effects", [])
        result.setdefault("reasoning", [])
        result.setdefault("confidence", [])
        result.setdefault("sources", [])
        result.setdefault("disclaimer", _DEFAULT_DISCLAIMER)

        # Attach raw literature context so the UI can display it
        result["literature_context"] = literature_context

        yield _sse({"status": "complete", "result": result})

    except Exception as exc:
        yield _sse({"status": "error", "message": str(exc)})
